### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by shanesample** [r1y5i/ktkkt-downloader#2]
'series' object is not subscriptable

Traceback (most recent call last):
  File "C:\Users\shane\__main__.py", line 112, in <module>
    download_series(args.url, args.directory)
  File "C:\Users\shane\__main__.py", line 15, in download_series
    products = scraper.get_products(url)
  File "C:\Users\shane\scraper.py", line 30, in get_products
    url = constant.SERIES_URL.format(series_id=get_series(url)['id'])
TypeError: 'Series' object is not subscriptable

**Comment by shanesample** [comment]
here is the line of code i gave it:

C:\Users\shane>python __main__.py -d D:\ktkkt\NARUTO -u https://www.ktkkt.top/movie/index8972.html -a

**Comment by shanesample** [comment]
it works for single episodes but not the entire series..(720 episodes).

**Comment by rkwyu** [comment]
Fixed, please update scraper.py to latest version.
